dist: xenial
language: python

cache:
  - pip

python:
  - '3.6'
  - '3.7'

addons:
  apt:
    packages:
      - mediainfo

before_script:
  - 'mkdir -p ~/{Music,Movies,Television}'

script:
  - pytest -v