dist: xenial
language: python

cache:
  - pip

python:
  - '3.6'
  - '3.7'

addons:
  apt:
    packages:
      - mediainfo

before_script:
  - 'wget https://github.com/JakeStanger/PMMS-Testing-Media/archive/master.zip'
  - 'unzip master.zip'
  - 'mv PMMS-Testing-Media-master/Music ~'
  - 'mv PMMS-Testing-Media-master/Movies ~'
  - 'mv PMMS-Testing-Media-master/Television ~'

script:
  - pytest -v --cov-report term --cov=./

after_success:
  - coveralls